"""Canonical funding sources used by the Fundello bot.

Generated from the same dataset as the public funding_sources.json file.
"""

from dataclasses import asdict, dataclass


@dataclass(frozen=True, slots=True)
class FundingSource:
    id: str
    name: str
    full_name: str
    category: str
    country: str
    max_amount: str
    is_recurring: bool
    recurring_details: str
    deadline: str
    difficulty: str
    eligibility: str
    tip: str
    contact_url: str
    contact_email: str


FUNDING_SOURCE_META: dict[str, int | str] = {"total":88,"categories":12,"description":"Finansieringskällor för Global Child Foundation — barnrättsorganisation Sverige","last_updated":"2025-06-07"}

FUNDING_CATEGORIES: list[dict[str, str | int]] = [
  {
    "id": "svensk-statlig",
    "label": "Svensk statlig",
    "badge_class": "badge-statlig",
    "count": 9
  },
  {
    "id": "svensk-stiftelse",
    "label": "Svensk stiftelse",
    "badge_class": "badge-stiftelse",
    "count": 12
  },
  {
    "id": "nordisk",
    "label": "Nordisk",
    "badge_class": "badge-nordisk",
    "count": 6
  },
  {
    "id": "eu-europa",
    "label": "EU/Europa",
    "badge_class": "badge-eu",
    "count": 6
  },
  {
    "id": "fn-multilateral",
    "label": "FN/Multilateral",
    "badge_class": "badge-fn",
    "count": 6
  },
  {
    "id": "internationell-stiftelse",
    "label": "Internationell stiftelse",
    "badge_class": "badge-intl",
    "count": 14
  },
  {
    "id": "teknik-csr",
    "label": "Teknik/CSR",
    "badge_class": "badge-teknik",
    "count": 9
  },
  {
    "id": "finans-bank",
    "label": "Finans/Bank",
    "badge_class": "badge-finans",
    "count": 4
  },
  {
    "id": "kyrka-trossamfund",
    "label": "Kyrka/Trossamfund",
    "badge_class": "badge-kyrka",
    "count": 4
  },
  {
    "id": "lotteri-insamling",
    "label": "Lotteri/Insamling",
    "badge_class": "badge-lotteri",
    "count": 3
  },
  {
    "id": "forskning-akademi",
    "label": "Forskning/Akademi",
    "badge_class": "badge-forskning",
    "count": 3
  },
  {
    "id": "ovaentad",
    "label": "Oväntad källa",
    "badge_class": "badge-ovaentad",
    "count": 12
  }
]

FUNDING_SOURCES: list[FundingSource] = [
    FundingSource(
        id="mucf",
        name="MUCF",
        full_name="Myndigheten för ungdoms- och civilsamhällesfrågor",
        category="svensk-statlig",
        country="Sverige",
        max_amount="500 000 SEK",
        is_recurring=True,
        recurring_details="Ansökan öppnar varje år, vanligtvis höst och vår",
        deadline="Se mucf.se för aktuella utlysningar",
        difficulty="Medium",
        eligibility="Ideella organisationer som arbetar med barn, unga och civilsamhälle i Sverige.",
        tip="MUCF prioriterar organisationer med demokratisk uppbyggnad och rikstäckande verksamhet. Visa medlemstal och lokal förankring.",
        contact_url="https://www.mucf.se/bidrag",
        contact_email="info@mucf.se",
    ),
    FundingSource(
        id="arvsfonden",
        name="Arvsfonden",
        full_name="Allmänna arvsfonden",
        category="svensk-statlig",
        country="Sverige",
        max_amount="5 000 000 SEK",
        is_recurring=True,
        recurring_details="Löpande ansökningar, beslut fattas löpande",
        deadline="Löpande",
        difficulty="Medium",
        eligibility="Ideella organisationer. Projektet ska vara nyskapande och komma barn, ungdomar eller personer med funktionsnedsättning till godo.",
        tip="Arvsfonden vill se innovativa metoder — inte ordinarie verksamhet. Bygg in utvärdering och spridning av resultat i ansökan.",
        contact_url="https://www.arvsfonden.se/sokabidrag",
        contact_email="info@arvsfonden.se",
    ),
    FundingSource(
        id="sida-civil",
        name="Sida — Civilsamhälle",
        full_name="Styrelsen för internationellt utvecklingssamarbete",
        category="svensk-statlig",
        country="Sverige",
        max_amount="10 000 000 SEK",
        is_recurring=True,
        recurring_details="Ramavtal förnyas vart 4–5 år, löpande projektbidrag",
        deadline="Varierar per utlysning",
        difficulty="Hög",
        eligibility="Svenska civilsamhällesorganisationer med internationell verksamhet. Kräver organisationsbidrag eller ramavtal.",
        tip="Sida kräver gedigen redovisningsförmåga och tydlig teorin om förändring (ToC). Börja med mindre projektbidrag innan ramavtal.",
        contact_url="https://www.sida.se/civilsamhallet",
        contact_email="sida@sida.se",
    ),
    FundingSource(
        id="forte",
        name="Forte",
        full_name="Forskningsrådet för hälsa, arbetsliv och välfärd",
        category="svensk-statlig",
        country="Sverige",
        max_amount="3 000 000 SEK",
        is_recurring=True,
        recurring_details="Utlysningar 2–3 gånger per år",
        deadline="Se forte.se för aktuella utlysningar",
        difficulty="Hög",
        eligibility="Kräver akademisk medverkande (PI vid universitet/högskola). NGO kan vara samarbetspart.",
        tip="Koppla ihop GCF med en forskargrupp vid t.ex. Stockholms universitet eller Linköping. Forte finansierar praktiknära forskning.",
        contact_url="https://forte.se/finansiering",
        contact_email="forte@forte.se",
    ),
    FundingSource(
        id="socialstyrelsen",
        name="Socialstyrelsen — Stimulansbidrag",
        full_name="Socialstyrelsen",
        category="svensk-statlig",
        country="Sverige",
        max_amount="2 000 000 SEK",
        is_recurring=True,
        recurring_details="Årliga utlysningar kopplade till regeringsuppdrag",
        deadline="Varierar, vanligtvis vår",
        difficulty="Medium",
        eligibility="Organisationer som arbetar med socialtjänst, barnskydd eller stöd till utsatta barn och familjer.",
        tip="Följ Socialstyrelsens regleringsbrev — stimulansmedel kopplas till specifika prioriteringsområden som ändras år för år.",
        contact_url="https://www.socialstyrelsen.se/bidrag",
        contact_email="socialstyrelsen@socialstyrelsen.se",
    ),
    FundingSource(
        id="folkhalsomyndigheten",
        name="Folkhälsomyndigheten",
        full_name="Folkhälsomyndigheten",
        category="svensk-statlig",
        country="Sverige",
        max_amount="1 000 000 SEK",
        is_recurring=True,
        recurring_details="Löpande och riktade utlysningar",
        deadline="Varierar",
        difficulty="Medium",
        eligibility="Ideella organisationer med hälsofrämjande arbete bland barn och unga.",
        tip="Koppla ansökan till ANDTS-strategin (alkohol, narkotika, dopning, tobak, spel) eller psykisk hälsa bland unga.",
        contact_url="https://www.folkhalsomyndigheten.se/bidrag",
        contact_email="info@folkhalsomyndigheten.se",
    ),
    FundingSource(
        id="bra",
        name="Brå — Brottsförebyggande rådet",
        full_name="Brottsförebyggande rådet",
        category="svensk-statlig",
        country="Sverige",
        max_amount="500 000 SEK",
        is_recurring=True,
        recurring_details="Utlysningar 1–2 gånger per år",
        deadline="Vanligtvis september–oktober",
        difficulty="Medium",
        eligibility="Organisationer med brottsförebyggande verksamhet, inkl. skydd av barn från exploatering.",
        tip="Fokusera på evidensbaserade metoder och mätbara effekter på brottslighet mot barn.",
        contact_url="https://www.bra.se/bidrag",
        contact_email="info@bra.se",
    ),
    FundingSource(
        id="migrationsverket",
        name="Migrationsverket — Projektbidrag",
        full_name="Migrationsverket",
        category="svensk-statlig",
        country="Sverige",
        max_amount="1 500 000 SEK",
        is_recurring=True,
        recurring_details="Löpande ansökningar",
        deadline="Löpande",
        difficulty="Medium",
        eligibility="Organisationer som arbetar med integration av ensamkommande barn och nyanlända familjer.",
        tip="Projekt som kombinerar barnrättsperspektiv med praktiskt integrationsarbete prioriteras.",
        contact_url="https://www.migrationsverket.se/bidrag",
        contact_email="migrationsverket@migrationsverket.se",
    ),
    FundingSource(
        id="lansstyrelserna",
        name="Länsstyrelserna",
        full_name="Länsstyrelserna (21 st)",
        category="svensk-statlig",
        country="Sverige",
        max_amount="300 000 SEK",
        is_recurring=True,
        recurring_details="Varje länsstyrelse har egna utlysningar, löpande",
        deadline="Varierar per län",
        difficulty="Låg",
        eligibility="Lokala och regionala organisationer. Varje länsstyrelse har egna prioriteringar, ofta hedersrelaterat våld, prostitution och trafficking.",
        tip="Kontakta länsstyrelsen i det/de län där GCF är verksamt. Hedersrelaterat våld mot barn är ett prioriterat område med öronmärkta medel.",
        contact_url="https://www.lansstyrelsen.se",
        contact_email="Se respektive länsstyrelses webbplats",
    ),
    FundingSource(
        id="world-childhood",
        name="World Childhood Foundation",
        full_name="World Childhood Foundation",
        category="svensk-stiftelse",
        country="Sverige / Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Projektbidrag, kan förnyas vid goda resultat",
        deadline="Letter of Interest accepteras löpande",
        difficulty="Hög",
        eligibility="Organisationer som skyddar barn från sexuellt utnyttjande och exploatering. Verksamma i Sverige, Moldavien, Sydafrika, Thailand eller Ukraina.",
        tip="Börja med ett Letter of Interest (LOI) på max 2 sidor. Stiftelsen grundades av Drottning Silvia — lyft kopplingen till det svenska barnrättsarbetet.",
        contact_url="https://childhood.org/grants",
        contact_email="grants@childhood.org",
    ),
    FundingSource(
        id="allmanna-barnhuset",
        name="Allmänna Barnhuset",
        full_name="Stiftelsen Allmänna Barnhuset",
        category="svensk-stiftelse",
        country="Sverige",
        max_amount="500 000 SEK",
        is_recurring=True,
        recurring_details="Utlysningar en gång per år, vanligtvis höst",
        deadline="Oktober–november varje år",
        difficulty="Medium",
        eligibility="Projekt för barn i utsatta situationer — misshandel, försummelse, familjevåld. Prioriterar kunskapsutveckling och metodstöd.",
        tip="Stiftelsen prioriterar forskning och metodutveckling framför ren verksamhetsdrift. Samarbete med akademi stärker ansökan.",
        contact_url="https://www.allmannabarnhuset.se",
        contact_email="info@allmannabarnhuset.se",
    ),
    FundingSource(
        id="skandia-ideas",
        name="Skandia — Idéer för livet",
        full_name="Stiftelsen Idéer för livet",
        category="svensk-stiftelse",
        country="Sverige",
        max_amount="1 000 000 SEK",
        is_recurring=True,
        recurring_details="En ansökningsomgång per år",
        deadline="Vanligtvis mars–april",
        difficulty="Medium",
        eligibility="Ideella organisationer som förebygger utanförskap bland unga. Fokus på tidiga insatser och föräldrastöd.",
        tip="Skandia vill se tydlig koppling till förebyggande av psykisk ohälsa och utanförskap. Lyft kostnad per hjälpt individ.",
        contact_url="https://www.ideerforlivet.se",
        contact_email="stiftelsen@ideerforlivet.se",
    ),
    FundingSource(
        id="ikea-foundation",
        name="IKEA Foundation",
        full_name="IKEA Foundation (Ingka Foundation)",
        category="svensk-stiftelse",
        country="Sverige / Global",
        max_amount="5 000 000 EUR",
        is_recurring=False,
        recurring_details="Strategiska partnerskap, ej öppna utlysningar",
        deadline="Ingen öppen ansökan — kontakta direkt",
        difficulty="Hög",
        eligibility="Stora, etablerade organisationer med bevisad kapacitet. Fokus på barn i flyktingsituationer och klimatutsatta familjer.",
        tip="IKEA Foundation söker sällan aktivt nya partners. Bygg relationer via nätverksmöten och konferenser. Visa impact i stor skala.",
        contact_url="https://www.ikeafoundation.org",
        contact_email="foundation@inter.ikea.com",
    ),
    FundingSource(
        id="hm-foundation",
        name="H&M Foundation",
        full_name="H&M Foundation",
        category="svensk-stiftelse",
        country="Sverige / Global",
        max_amount="2 000 000 USD",
        is_recurring=False,
        recurring_details="Global Change Award + direktfinansieringar",
        deadline="Global Change Award: september varje år",
        difficulty="Hög",
        eligibility="Innovativa lösningar för jämlikhet och hållbarhet. Barnrättsprojekt med tydlig skalbarhet.",
        tip="H&M Foundation vill se innovativa, skalbara lösningar. Koppla barnrättsperspektivet till hållbarhetsmålen (SDGs).",
        contact_url="https://hmfoundation.com",
        contact_email="foundation@hm.com",
    ),
    FundingSource(
        id="postkodstiftelsen",
        name="PostkodStiftelsen",
        full_name="Svenska PostkodStiftelsen",
        category="svensk-stiftelse",
        country="Sverige / Global",
        max_amount="3 000 000 SEK",
        is_recurring=False,
        recurring_details="En–två utlysningar per år",
        deadline="Varierar, se postkodstiftelsen.se",
        difficulty="Medium",
        eligibility="Ideella organisationer med projekt för miljö, mänskliga rättigheter eller socialt utsatta grupper inkl. barn.",
        tip="PostkodStiftelsen finansierar gärna projekt utanför Sverige. Tydlig impact-mätning och transparens är avgörande.",
        contact_url="https://postkodstiftelsen.se",
        contact_email="info@postkodstiftelsen.se",
    ),
    FundingSource(
        id="familjen-kamprads",
        name="Familjen Kamprads Stiftelse",
        full_name="Familjen Kamprads Stiftelse",
        category="svensk-stiftelse",
        country="Sverige",
        max_amount="2 000 000 SEK",
        is_recurring=False,
        recurring_details="Löpande ansökningar",
        deadline="Löpande",
        difficulty="Medium",
        eligibility="Svenska organisationer med projekt för utsatta barn och äldre. Fokus på praktisk nytta och kostnadseffektivitet.",
        tip="Stiftelsen värdesätter enkelhet och konkreta resultat. Undvik byråkratiskt språk — skriv om verklig förändring för riktiga barn.",
        contact_url="https://www.familjenkampradsstiftelse.se",
        contact_email="info@familjenkampradsstiftelse.se",
    ),
    FundingSource(
        id="svenska-spel-gras",
        name="Svenska Spel — Gräsrotsbidrag",
        full_name="Svenska Spel Gräsrotsbidrag",
        category="svensk-stiftelse",
        country="Sverige",
        max_amount="Beror på spelarnas val",
        is_recurring=True,
        recurring_details="Löpande — spelarna väljer vilken förening de stödjer",
        deadline="Löpande registrering",
        difficulty="Låg",
        eligibility="Ideella föreningar registrerade i Sverige med organisationsnummer.",
        tip="Registrera GCF och marknadsför aktivt till befintliga supportrar att välja er. Liten insats, passiv inkomst.",
        contact_url="https://www.svenskaspel.se/grasrot",
        contact_email="grasrot@svenskaspel.se",
    ),
    FundingSource(
        id="axfoundation",
        name="Axfoundation",
        full_name="Axfoundation",
        category="svensk-stiftelse",
        country="Sverige",
        max_amount="1 000 000 SEK",
        is_recurring=False,
        recurring_details="Projektbaserat, löpande dialog",
        deadline="Ingen öppen utlysning — kontakta direkt",
        difficulty="Hög",
        eligibility="Projekt inom hållbar mat, socialt ansvar och utsatta samhällsgrupper inkl. barn.",
        tip="Axfoundation arbetar i partnerskap snarare än traditionell grantgiving. Initiera dialog om gemensamma intressen.",
        contact_url="https://www.axfoundation.se",
        contact_email="info@axfoundation.se",
    ),
    FundingSource(
        id="fryshuset",
        name="Stiftelsen Fryshuset",
        full_name="Stiftelsen Fryshuset",
        category="svensk-stiftelse",
        country="Sverige",
        max_amount="300 000 SEK",
        is_recurring=False,
        recurring_details="Samarbetsprojekt och partnerskap",
        deadline="Löpande dialog",
        difficulty="Medium",
        eligibility="Organisationer som arbetar med unga i utanförskap, särskilt i storstadsregioner.",
        tip="Fryshuset är mer intresserade av samarbete och kunskapsdelning än ren bidragsgivning. Föreslå ett gemensamt projekt.",
        contact_url="https://www.fryshuset.se",
        contact_email="info@fryshuset.se",
    ),
    FundingSource(
        id="radda-barnen-fond",
        name="Rädda Barnen — Projektbidrag",
        full_name="Rädda Barnen Sverige",
        category="svensk-stiftelse",
        country="Sverige",
        max_amount="500 000 SEK",
        is_recurring=False,
        recurring_details="Partnerorganisationer kan söka projektbidrag",
        deadline="Varierar",
        difficulty="Hög",
        eligibility="Organisationer med komplementär verksamhet till Rädda Barnens kärnuppdrag. Kräver etablerad relation.",
        tip="Rädda Barnen ger sällan bidrag till liknande organisationer utan föredrar samarbetsavtal. Positionera GCF som komplement, inte konkurrent.",
        contact_url="https://www.raddabarnen.se/samarbete",
        contact_email="info@raddabarnen.se",
    ),
    FundingSource(
        id="sff-frimurare",
        name="Svenska Frimurare Orden",
        full_name="Svenska Frimurare Ordens Barnfond",
        category="svensk-stiftelse",
        country="Sverige",
        max_amount="200 000 SEK",
        is_recurring=True,
        recurring_details="Ansökan en gång per år",
        deadline="Vanligtvis januari–februari",
        difficulty="Låg",
        eligibility="Svenska organisationer med arbete för utsatta barn. Bred tolkning av barnrättsarbete.",
        tip="Ordens barnfond är relativt okänd och har lägre konkurrens. Personlig kontakt med en lokal loge ökar chanserna markant.",
        contact_url="https://www.frimurarorden.se/barnfonden",
        contact_email="barnfonden@frimurarorden.se",
    ),
    FundingSource(
        id="nordea-foundation",
        name="Nordea Foundation",
        full_name="Nordea Foundation",
        category="nordisk",
        country="Norden",
        max_amount="1 000 000 DKK",
        is_recurring=True,
        recurring_details="Löpande ansökningar, beslut kvartalsvis",
        deadline="Löpande",
        difficulty="Medium",
        eligibility="Nordiska ideella organisationer med social impact. Fokus på välmående, rörelse och gemenskap.",
        tip="Nordea Foundation fokuserar på aktiva liv och socialt välmående. Lyft hur GCF:s arbete bidrar till barns välmående och aktiva deltagande i samhället.",
        contact_url="https://nordeafonden.dk/en/apply",
        contact_email="nordeafonden@nordea.com",
    ),
    FundingSource(
        id="nordic-ministerradet",
        name="Nordiska ministerrådet",
        full_name="Nordiska ministerrådet",
        category="nordisk",
        country="Norden",
        max_amount="500 000 DKK",
        is_recurring=True,
        recurring_details="Utlysningar kopplade till nordiska prioriteringar, löpande",
        deadline="Varierar per program",
        difficulty="Medium",
        eligibility="Organisationer i de nordiska länderna. Projekt med nordiskt mervärde och samarbete.",
        tip="Nordisk samverkan är ett krav — samarbeta med en organisation i minst ett annat nordiskt land.",
        contact_url="https://www.norden.org/sv/funding",
        contact_email="info@norden.org",
    ),
    FundingSource(
        id="oak-foundation",
        name="Oak Foundation",
        full_name="Oak Foundation",
        category="nordisk",
        country="Schweiz / Global",
        max_amount="2 000 000 USD",
        is_recurring=False,
        recurring_details="Fleråriga partnerskap med utvalda organisationer",
        deadline="Ingen öppen ansökan — inbjudningsbaserat",
        difficulty="Hög",
        eligibility="Organisationer som bekämpar sexuellt utnyttjande av barn, trafficking och våld. Starka krav på kapacitet och governance.",
        tip="Oak Foundation arbetar med ett fåtal utvalda partners. Bygg synlighet genom publikationer, konferenser och media. De hittar er.",
        contact_url="https://oakfnd.org/programmes/child-abuse",
        contact_email="apply@oakfnd.org",
    ),
    FundingSource(
        id="novo-nordisk-foundation",
        name="Novo Nordisk Foundation",
        full_name="Novo Nordisk Foundation",
        category="nordisk",
        country="Danmark / Global",
        max_amount="5 000 000 DKK",
        is_recurring=False,
        recurring_details="Specifika utlysningar inom hälsa och social välfärd",
        deadline="Varierar per utlysning",
        difficulty="Hög",
        eligibility="Forskning och innovation inom hälsa. NGO-projekt kräver akademisk partner.",
        tip="Novo Nordisk Foundation finansierar i huvudsak forskning. Koppla barnrättsarbetet till hälsoutfall — psykisk hälsa, näringslära, tidig utveckling.",
        contact_url="https://novonordiskfonden.dk/en/grants",
        contact_email="nnf@novonordiskfonden.dk",
    ),
    FundingSource(
        id="villum-foundation",
        name="Villum Foundation",
        full_name="VILLUM FONDEN",
        category="nordisk",
        country="Danmark",
        max_amount="2 000 000 DKK",
        is_recurring=False,
        recurring_details="Löpande ansökningar inom sociala program",
        deadline="Löpande",
        difficulty="Hög",
        eligibility="Danska och nordiska organisationer inom teknik, natur och socialt arbete.",
        tip="Villum Foundations sociala program är mindre känt och har lägre konkurrens än teknikprogrammen. Fokusera på innovation i socialt arbete.",
        contact_url="https://villumfonden.dk/en/apply",
        contact_email="villumfonden@villumfonden.dk",
    ),
    FundingSource(
        id="ramboll-foundation",
        name="Rambøll Foundation",
        full_name="Rambøll Foundation",
        category="nordisk",
        country="Danmark",
        max_amount="500 000 DKK",
        is_recurring=False,
        recurring_details="Projektbidrag, löpande",
        deadline="Löpande",
        difficulty="Medium",
        eligibility="Sociala innovationsprojekt i Norden. Barn och ungas rättigheter.",
        tip="Rambøll Foundation kombinerar gärna bidrag med rådgivning från Rambøll-koncernens konsulter. Erbjud dem att bidra med kompetens.",
        contact_url="https://ramboll.com/foundation",
        contact_email="foundation@ramboll.com",
    ),
    FundingSource(
        id="eu-cerv",
        name="EU — CERV",
        full_name="Citizens, Equality, Rights and Values Programme",
        category="eu-europa",
        country="EU",
        max_amount="500 000 EUR",
        is_recurring=True,
        recurring_details="Utlysningar 2–3 gånger per år inom olika temaområden",
        deadline="Se ec.europa.eu/info/funding-tenders för aktuella calls",
        difficulty="Hög",
        eligibility="Organisationer registrerade i EU-länder. Projekt om barnrättigheter, jämlikhet, medborgarengagemang.",
        tip="CERV kräver minst 3 partners från olika EU-länder. Sök på funding.europa.eu. Börja med mindre Action Grants (max 60 000 EUR) för erfarenhet.",
        contact_url="https://ec.europa.eu/info/funding-tenders/opportunities/portal",
        contact_email="Se resp. utlysning på portalen",
    ),
    FundingSource(
        id="esf-plus",
        name="ESF+ — Strukturfonder",
        full_name="Europeiska socialfonden+",
        category="eu-europa",
        country="EU / Sverige",
        max_amount="5 000 000 SEK",
        is_recurring=True,
        recurring_details="Utlysningar via Svenska ESF-rådet, löpande",
        deadline="Se esf.se för aktuella utlysningar",
        difficulty="Hög",
        eligibility="Svenska organisationer. Projekt om social inkludering, sysselsättning och utbildning för utsatta grupper inkl. barn.",
        tip="ESF+ kräver medfinansiering (vanligtvis 50%). Samarbeta med en kommun eller region för att täcka egeninsatsen.",
        contact_url="https://www.esf.se/sv/Fonder-och-program/Socialfonden",
        contact_email="esf@esf.se",
    ),
    FundingSource(
        id="coe-human-rights",
        name="Europarådet — Human Rights Fund",
        full_name="Council of Europe Human Rights Trust Fund",
        category="eu-europa",
        country="Europa",
        max_amount="200 000 EUR",
        is_recurring=False,
        recurring_details="Specifika utlysningar",
        deadline="Varierar per utlysning",
        difficulty="Hög",
        eligibility="Organisationer i Europarådets medlemsländer. Projekt om mänskliga rättigheter inkl. barnrättigheter.",
        tip="Koppla till Europarådets Lanzarote-konvention om skydd av barn mot sexuell exploatering.",
        contact_url="https://www.coe.int/en/web/human-rights-trust-fund",
        contact_email="humanrightsfund@coe.int",
    ),
    FundingSource(
        id="eea-norway-grants",
        name="EEA & Norway Grants",
        full_name="EEA and Norway Grants",
        category="eu-europa",
        country="Europa",
        max_amount="1 000 000 EUR",
        is_recurring=False,
        recurring_details="Programperioder vart 5–7 år, nästa period 2026+",
        deadline="Varierar per land och program",
        difficulty="Hög",
        eligibility="Organisationer i mottagarländer (Bulgarien, Kroatien, Tjeckien, Estland m.fl.). Kräver partner i Norge, Island eller Liechtenstein.",
        tip="GCF kan vara norsk/nordisk partner i projekt ledda av organisation i ett mottagarland. Kontakta östeuropeiska barnrättsorganisationer.",
        contact_url="https://www.eeagrants.org",
        contact_email="eeagrants@efta.int",
    ),
    FundingSource(
        id="daphne",
        name="Daphne-programmet",
        full_name="Daphne (del av EU CERV)",
        category="eu-europa",
        country="EU",
        max_amount="400 000 EUR",
        is_recurring=True,
        recurring_details="Utlysningar 1–2 gånger per år",
        deadline="Se CERV-portalen",
        difficulty="Hög",
        eligibility="EU-baserade organisationer. Fokus på förebyggande av våld mot barn, unga och kvinnor.",
        tip="Daphne är nu en del av CERV men har bibehållit sitt fokus på våld mot barn. Tydlig koppling till våldsförebyggande arbete är avgörande.",
        contact_url="https://ec.europa.eu/info/funding-tenders/opportunities/portal",
        contact_email="Se CERV-portalen",
    ),
    FundingSource(
        id="eu-solidarity-corps",
        name="EU — European Solidarity Corps",
        full_name="European Solidarity Corps",
        category="eu-europa",
        country="EU",
        max_amount="50 000 EUR",
        is_recurring=True,
        recurring_details="Löpande ansökningar",
        deadline="Löpande",
        difficulty="Medium",
        eligibility="Organisationer som kan ta emot volontärer 18–30 år. Passar GCF för att rekrytera engagerade unga.",
        tip="Solidarity Corps finansierar inte projekt direkt men ger gratis volontärer som kan bidra med kapacitet. Utmärkt för sociala medieprojekt.",
        contact_url="https://europa.eu/youth/solidarity_sv",
        contact_email="eac-youth@ec.europa.eu",
    ),
    FundingSource(
        id="unicef-partnership",
        name="UNICEF — Partnership Fund",
        full_name="UNICEF Partnership Fund for Children",
        category="fn-multilateral",
        country="Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Utvalda partnerskap, ej öppen ansökan",
        deadline="Kontakta UNICEF Sverige direkt",
        difficulty="Hög",
        eligibility="Etablerade organisationer med bevisad kapacitet inom barnrättsarbete. Kräver samstämmighet med UNICEFs program.",
        tip="Kontakta UNICEF Sveriges nationella kontor. Positionera GCF som implementeringspartner snarare än självständig sökande.",
        contact_url="https://www.unicef.se/samarbete",
        contact_email="info@unicef.se",
    ),
    FundingSource(
        id="unodc-trafficking",
        name="UNODC — Trafficking Fund",
        full_name="UNODC United Nations Office on Drugs and Crime",
        category="fn-multilateral",
        country="Global",
        max_amount="300 000 USD",
        is_recurring=False,
        recurring_details="Projektspecifika utlysningar",
        deadline="Varierar per utlysning",
        difficulty="Hög",
        eligibility="Organisationer som arbetar mot trafficking och exploatering av barn. Kräver FN-ackreditering eller partnerskap.",
        tip="UNODC fokuserar på trafficking och organiserad brottslighet. Koppla barnrättsarbetet tydligt till anti-trafficking om relevant.",
        contact_url="https://www.unodc.org/unodc/en/human-trafficking/index.html",
        contact_email="unodc@un.org",
    ),
    FundingSource(
        id="ohchr",
        name="OHCHR — UN Human Rights",
        full_name="Office of the High Commissioner for Human Rights",
        category="fn-multilateral",
        country="Global",
        max_amount="200 000 USD",
        is_recurring=False,
        recurring_details="Specifika utlysningar och partnerskap",
        deadline="Varierar",
        difficulty="Hög",
        eligibility="Organisationer med fokus på mänskliga rättigheter inkl. barnets rättigheter (CRC).",
        tip="OHCHR finansierar i hög grad rapporterings- och påverkansarbete. Engagera GCF i rapportering till FN:s barnrättskommitté.",
        contact_url="https://www.ohchr.org/en/aboutus/civil-society",
        contact_email="civilsociety@ohchr.org",
    ),
    FundingSource(
        id="un-women",
        name="UN Women — Fund for Gender Equality",
        full_name="UN Women Fund for Gender Equality",
        category="fn-multilateral",
        country="Global",
        max_amount="1 000 000 USD",
        is_recurring=True,
        recurring_details="Utlysningar ca vartannat år",
        deadline="Se unwomen.org för nästa utlysning",
        difficulty="Hög",
        eligibility="Organisationer som arbetar med flickors rättigheter och könsbaserat våld mot barn.",
        tip="Fokusera på flickor och könsbaserat våld om det är relevant för GCF. Koppla till SDG 5 (jämställdhet).",
        contact_url="https://www.unwomen.org/en/trust-funds/fund-for-gender-equality",
        contact_email="fge@unwomen.org",
    ),
    FundingSource(
        id="global-fund-children",
        name="Global Fund for Children",
        full_name="Global Fund for Children",
        category="fn-multilateral",
        country="Global",
        max_amount="30 000 USD",
        is_recurring=True,
        recurring_details="Löpande ansökningar för gräsrotsorganisationer",
        deadline="Löpande",
        difficulty="Medium",
        eligibility="Gräsrotsorganisationer med budget under 1M USD. Fokus på de mest utsatta barnen globalt.",
        tip="GFC är idealisk för unga organisationer. Beloppen är små men relationen och nätverket är ovärderliga. Utmärkt som first grant.",
        contact_url="https://www.globalfundforchildren.org/apply",
        contact_email="grants@globalfundforchildren.org",
    ),
    FundingSource(
        id="unfpa",
        name="UNFPA",
        full_name="United Nations Population Fund",
        category="fn-multilateral",
        country="Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Specifika utlysningar och implementeringspartnerskap",
        deadline="Varierar",
        difficulty="Hög",
        eligibility="Organisationer som arbetar mot barnäktenskap, könsstympning och sexuell och reproduktiv hälsa för unga.",
        tip="UNFPA fokuserar på barnäktenskap och flickors rättigheter. Relevant om GCF arbetar internationellt i dessa frågor.",
        contact_url="https://www.unfpa.org/partners/civil-society",
        contact_email="cspartners@unfpa.org",
    ),
    FundingSource(
        id="gates-foundation",
        name="Bill & Melinda Gates Foundation",
        full_name="Bill & Melinda Gates Foundation",
        category="internationell-stiftelse",
        country="USA / Global",
        max_amount="5 000 000 USD",
        is_recurring=False,
        recurring_details="Strategiska partnerskap, ej öppen ansökan",
        deadline="Ingen öppen ansökan — Grand Challenges-utlysningar ibland",
        difficulty="Hög",
        eligibility="Stora, etablerade organisationer. Grand Challenges är öppnare — ansök via grand challenges.org.",
        tip="Börja med Gates Grand Challenges-utlysningar som är öppna. Fokusera på innovation och tekniska lösningar för barnhälsa.",
        contact_url="https://www.gatesfoundation.org/about/how-we-work/grantseeker-faq",
        contact_email="grantsmanagement@gatesfoundation.org",
    ),
    FundingSource(
        id="kellogg-foundation",
        name="W.K. Kellogg Foundation",
        full_name="W.K. Kellogg Foundation",
        category="internationell-stiftelse",
        country="USA / Global",
        max_amount="1 000 000 USD",
        is_recurring=False,
        recurring_details="Löpande ansökningar",
        deadline="Löpande",
        difficulty="Hög",
        eligibility="Organisationer i USA, Mexiko, Haiti och södra Afrika. Internationella partners kan söka via US-baserade organisationer.",
        tip="Kellogg Foundation fokuserar på Educated Kids, Healthy Kids och Secure Families. Etablera partnerskap med en US-baserad organisation.",
        contact_url="https://www.wkkf.org/grants/apply",
        contact_email="grantsandinfo@wkkf.org",
    ),
    FundingSource(
        id="ford-foundation",
        name="Ford Foundation",
        full_name="Ford Foundation",
        category="internationell-stiftelse",
        country="USA / Global",
        max_amount="2 000 000 USD",
        is_recurring=False,
        recurring_details="Inbjudningsbaserat, ej öppen ansökan",
        deadline="Ingen öppen ansökan",
        difficulty="Hög",
        eligibility="Organisationer med fokus på ojämlikhet, demokrati och mänskliga rättigheter.",
        tip="Ford Foundation arbetar med ett fåtal utvalda partners per region. Bygg synlighet i internationella nätverk och publikationer.",
        contact_url="https://www.fordfoundation.org/work/our-grants/applying-for-a-grant",
        contact_email="Se respektive regionalkontor",
    ),
    FundingSource(
        id="open-society",
        name="Open Society Foundations",
        full_name="Open Society Foundations",
        category="internationell-stiftelse",
        country="USA / Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Inbjudningsbaserat per program",
        deadline="Kontakta relevant programkontor",
        difficulty="Hög",
        eligibility="Organisationer som arbetar för öppna samhällen, rättvisa och rättigheter. Barnrättsarbete med fokus på marginaliserade grupper.",
        tip="Open Society har regionala kontor — kontakta det europeiska. Fokusera på Roma-barn, flyktingbarn eller statslösa barn för bäst matchning.",
        contact_url="https://www.opensocietyfoundations.org/grants",
        contact_email="grants@opensocietyfoundations.org",
    ),
    FundingSource(
        id="macarthur-foundation",
        name="MacArthur Foundation",
        full_name="John D. and Catherine T. MacArthur Foundation",
        category="internationell-stiftelse",
        country="USA",
        max_amount="1 000 000 USD",
        is_recurring=False,
        recurring_details="Inbjudningsbaserat",
        deadline="Ingen öppen ansökan",
        difficulty="Hög",
        eligibility="Internationella organisationer med fokus på kärnsociala frågor. 100&Change: $100M-pris för en organisation.",
        tip="Bevaka MacArthur 100&Change-utlysningen — öppen för alla och kan ge transformativa medel. Kräver extraordinär impact-vision.",
        contact_url="https://www.macfound.org/info-grantseekers/grantmaking-policies-and-practices",
        contact_email="4answers@macfound.org",
    ),
    FundingSource(
        id="hewlett-foundation",
        name="Hewlett Foundation",
        full_name="William & Flora Hewlett Foundation",
        category="internationell-stiftelse",
        country="USA",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Inbjudningsbaserat",
        deadline="Ingen öppen ansökan",
        difficulty="Hög",
        eligibility="Organisationer med fokus på utbildning, global utveckling och demokrati.",
        tip="Hewlett fokuserar på bevisbaserade metoder (evidence-based). Starka utvärderingsdata är avgörande för att väcka intresse.",
        contact_url="https://www.hewlett.org/grants",
        contact_email="grantsinquiries@hewlett.org",
    ),
    FundingSource(
        id="ciff",
        name="CIFF — Children's Investment Fund",
        full_name="Children's Investment Fund Foundation",
        category="internationell-stiftelse",
        country="UK / Global",
        max_amount="5 000 000 GBP",
        is_recurring=False,
        recurring_details="Fleråriga strategiska partnerskap",
        deadline="Inbjudningsbaserat",
        difficulty="Hög",
        eligibility="Stora organisationer med bevisad kapacitet och impact. Fokus på undernäring, flickors utbildning och klimat.",
        tip="CIFF finansierar storskaliga interventioner. Positionera GCF som en del av en större impact-koalition.",
        contact_url="https://ciff.org/grant-portfolio",
        contact_email="enquiries@ciff.org",
    ),
    FundingSource(
        id="sigrid-rausing",
        name="Sigrid Rausing Trust",
        full_name="Sigrid Rausing Trust",
        category="internationell-stiftelse",
        country="UK / Global",
        max_amount="300 000 GBP",
        is_recurring=False,
        recurring_details="Löpande ansökningar",
        deadline="Löpande",
        difficulty="Hög",
        eligibility="Organisationer med fokus på mänskliga rättigheter, inkl. barnrättigheter och kampen mot trafficking.",
        tip="Sigrid Rausing Trust har ett starkt fokus på östra Europa och Central Asien. Koppla GCF:s arbete till dessa regioner.",
        contact_url="https://www.sigrid-rausing-trust.org/Grants/How-to-Apply",
        contact_email="info@srtrust.org",
    ),
    FundingSource(
        id="bernard-van-leer",
        name="Bernard van Leer Foundation",
        full_name="Bernard van Leer Foundation",
        category="internationell-stiftelse",
        country="Nederländerna / Global",
        max_amount="500 000 EUR",
        is_recurring=False,
        recurring_details="Strategiska partnerskap",
        deadline="Inbjudningsbaserat — skicka Expression of Interest",
        difficulty="Hög",
        eligibility="Organisationer med fokus på tidiga barndomen (0–5 år). Stadsplanering, föräldraskap och tidig barndom.",
        tip="Van Leer är unik i sitt fokus på urbana miljöer och de allra yngsta barnen. Koppla barnrättsarbetet till tidig barndom om möjligt.",
        contact_url="https://bernardvanleer.org/apply-for-funding",
        contact_email="info@bvleerf.nl",
    ),
    FundingSource(
        id="comic-relief",
        name="Comic Relief / Sport Relief",
        full_name="Comic Relief",
        category="internationell-stiftelse",
        country="UK",
        max_amount="500 000 GBP",
        is_recurring=True,
        recurring_details="Utlysningar i samband med Red Nose Day och Sport Relief",
        deadline="Vartannat år (Red Nose Day = udda år)",
        difficulty="Medium",
        eligibility="UK-baserade organisationer och internationella partners. Fokus på att avsluta fattigdom och social orättvisa.",
        tip="Partnera med en UK-baserad organisation för att söka. Comic Relief har öppna utlysningar för internationella projekt.",
        contact_url="https://www.comicrelief.com/your-impact/how-we-fund",
        contact_email="grantsinfo@comicrelief.com",
    ),
    FundingSource(
        id="elton-john-aids",
        name="Elton John AIDS Foundation",
        full_name="Elton John AIDS Foundation",
        category="internationell-stiftelse",
        country="Global",
        max_amount="300 000 USD",
        is_recurring=False,
        recurring_details="Specifika utlysningar",
        deadline="Varierar",
        difficulty="Medium",
        eligibility="Organisationer med fokus på hiv/aids hos barn och unga, särskilt i fattiga länder.",
        tip="Relevant om GCF arbetar med barn och hiv/aids. Kopplingen till barnens rättigheter och hälsa är central.",
        contact_url="https://www.ejaf.com/grants",
        contact_email="grants@ejaf.org",
    ),
    FundingSource(
        id="mott-foundation",
        name="Mott Foundation",
        full_name="Charles Stewart Mott Foundation",
        category="internationell-stiftelse",
        country="USA / Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Inbjudningsbaserat för internationella projekt",
        deadline="Ingen öppen ansökan",
        difficulty="Hög",
        eligibility="Civilsamhällesorganisationer globalt. Fokus på demokrati, miljö och ekonomisk rättvisa.",
        tip="Mott stödjer civilsamhällets kapacitetsbyggande. Positionera GCF som en stark civilsamhällesröst för barnrättigheter.",
        contact_url="https://www.mott.org/grants/apply",
        contact_email="See website for regional contacts",
    ),
    FundingSource(
        id="luminate",
        name="Luminate",
        full_name="Luminate Foundation",
        category="internationell-stiftelse",
        country="Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Strategiska partnerskap",
        deadline="Inbjudningsbaserat",
        difficulty="Hög",
        eligibility="Organisationer som arbetar med digital rättigheter, öppenhet och medborgardeltagande. Barnrättigheter online.",
        tip="Luminate fokuserar på digitala rättigheter. Barns onlinesäkerhet och digitala rättigheter är ett växande fokusområde.",
        contact_url="https://luminategroup.com/what-we-fund",
        contact_email="hello@luminategroup.com",
    ),
    FundingSource(
        id="hilton-foundation",
        name="Conrad Hilton Foundation",
        full_name="Conrad N. Hilton Foundation",
        category="internationell-stiftelse",
        country="USA / Global",
        max_amount="1 000 000 USD",
        is_recurring=False,
        recurring_details="Inbjudningsbaserat + öppna utlysningar",
        deadline="Humanitarianpriset: maj varje år",
        difficulty="Hög",
        eligibility="Organisationer inom katolsk socialvård, barnomsorg och humanitärt arbete.",
        tip="Hilton Prize är öppet för alla — $2M till en organisation. Nom. en gång per år. Fokus på transformativ humanitär insats.",
        contact_url="https://www.hiltonfoundation.org/grants",
        contact_email="grants@hiltonfoundation.org",
    ),
    FundingSource(
        id="microsoft-philanthropies",
        name="Microsoft Philanthropies",
        full_name="Microsoft Philanthropies",
        category="teknik-csr",
        country="Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Teknikdonationer löpande, kontantbidrag via utlysningar",
        deadline="Löpande för teknikdonationer",
        difficulty="Medium",
        eligibility="Ideella organisationer globalt. Microsoft erbjuder mjukvara, molntjänster (Azure credits) och kontantbidrag.",
        tip="Börja med Microsoft for Nonprofits — gratis Office 365, Azure-krediter och Dynamics 365. Konantbidrag söks separat och är mer konkurrensbaserat.",
        contact_url="https://www.microsoft.com/en-us/nonprofits",
        contact_email="npoinfo@microsoft.com",
    ),
    FundingSource(
        id="google-org",
        name="Google.org",
        full_name="Google.org",
        category="teknik-csr",
        country="Global",
        max_amount="1 000 000 USD",
        is_recurring=False,
        recurring_details="Utlysningar och inbjudningsbaserat",
        deadline="Löpande för Google Ad Grants, bidrag via utlysning",
        difficulty="Hög",
        eligibility="Ideella organisationer. Google Ad Grants ger $10 000/mån i gratisannonsering — starkt rekommenderat.",
        tip="Ansök om Google Ad Grants OMEDELBART — $10 000/mån i Google Ads är gratis och kan driva donationer och synlighet. Bidrag från Google.org är mer selektivt.",
        contact_url="https://www.google.org/apply",
        contact_email="nonprofits@google.com",
    ),
    FundingSource(
        id="meta-safety",
        name="Meta — Safety Fund",
        full_name="Meta Online Safety Fund",
        category="teknik-csr",
        country="Global",
        max_amount="200 000 USD",
        is_recurring=False,
        recurring_details="Specifika utlysningar kopplade till reglering",
        deadline="Varierar",
        difficulty="Medium",
        eligibility="Organisationer som arbetar med onlinesäkerhet, CSAM och barnens digitala rättigheter.",
        tip="Meta finansierar organisationer som komplement till deras Trust & Safety-arbete. Tydlig koppling till barns onlinesäkerhet är nyckeln.",
        contact_url="https://about.fb.com/news/2021/10/metas-online-safety-fund",
        contact_email="safety@fb.com",
    ),
    FundingSource(
        id="cisco-foundation",
        name="Cisco Foundation",
        full_name="Cisco Foundation",
        category="teknik-csr",
        country="Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Löpande ansökningar",
        deadline="Löpande",
        difficulty="Medium",
        eligibility="Organisationer som använder teknik för samhällsnytta. Barn och utbildning är prioriterade.",
        tip="Cisco erbjuder teknologidonationer via Cisco Networking Academy och kontantbidrag via Cisco Foundation. Kombinera teknik + socialt syfte.",
        contact_url="https://www.cisco.com/c/en/us/about/csr/community/nonprofits.html",
        contact_email="csr@cisco.com",
    ),
    FundingSource(
        id="thorn-tech-coalition",
        name="Thorn / Tech Coalition",
        full_name="Thorn + The Tech Coalition",
        category="teknik-csr",
        country="Global",
        max_amount="100 000 USD",
        is_recurring=False,
        recurring_details="Partnerskap och projektfinansiering",
        deadline="Kontakta direkt",
        difficulty="Medium",
        eligibility="Organisationer som bekämpar CSAM och online-exploatering av barn. Teknikfokus.",
        tip="Thorn söker aktivt samarbetspartners. Fokusera på tekniska lösningar mot CSAM och onlinesäkerhet för barn.",
        contact_url="https://www.thorn.org/partners",
        contact_email="partners@thorn.org",
    ),
    FundingSource(
        id="netclean",
        name="NetClean / Qognify",
        full_name="NetClean Technologies",
        category="teknik-csr",
        country="Sverige / Global",
        max_amount="100 000 SEK",
        is_recurring=False,
        recurring_details="CSR-partnerskap",
        deadline="Kontakta direkt",
        difficulty="Låg",
        eligibility="Svenska organisationer som arbetar mot CSAM och exploatering av barn online.",
        tip="NetClean är ett göteborgbaserat företag som är starkt engagerat i barnrättsfrågor. De söker aktivt samarbetspartners och kan bidra med både pengar och kompetens.",
        contact_url="https://www.netclean.com/about-us/corporate-social-responsibility",
        contact_email="info@netclean.com",
    ),
    FundingSource(
        id="iwf",
        name="Internet Watch Foundation",
        full_name="Internet Watch Foundation",
        category="teknik-csr",
        country="UK / Global",
        max_amount="50 000 GBP",
        is_recurring=False,
        recurring_details="Partnerskap och projektfinansiering",
        deadline="Kontakta direkt",
        difficulty="Medium",
        eligibility="Organisationer som arbetar mot online CSAM. IWF finansierar kompletterande insatser.",
        tip="IWF finansierar utbildnings- och medvetenhetsprojekt om online-sexuell exploatering av barn. Bra matchning för GCF.",
        contact_url="https://www.iwf.org.uk/about-us/partnerships",
        contact_email="info@iwf.org.uk",
    ),
    FundingSource(
        id="salesforce-org",
        name="Salesforce.org",
        full_name="Salesforce.org",
        category="teknik-csr",
        country="Global",
        max_amount="100 000 USD",
        is_recurring=False,
        recurring_details="Löpande teknikdonationer, bidrag via utlysningar",
        deadline="Löpande för Nonprofit Success Pack (NPSP)",
        difficulty="Låg",
        eligibility="Alla ideella organisationer kan få Salesforce gratis (10 licenser). Kontantbidrag mer selektivt.",
        tip="Registrera GCF för gratis Salesforce NPSP — kraftfullt CRM för donationshantering, kontakter och rapportering. Transformativt för organisationskapacitet.",
        contact_url="https://www.salesforce.org/nonprofit",
        contact_email="nonprofits@salesforce.com",
    ),
    FundingSource(
        id="apple-giving",
        name="Apple — Employee Giving / CSR",
        full_name="Apple Corporate Social Responsibility",
        category="teknik-csr",
        country="Global",
        max_amount="50 000 USD",
        is_recurring=False,
        recurring_details="Employee Giving — Apple matchar anställdas donationer",
        deadline="Löpande via Apple Giving Program",
        difficulty="Medium",
        eligibility="Registrerade ideella organisationer. Apple matchar anställdas donationer dollar-för-dollar.",
        tip="Rekrytera Apple-anställda som månadsgivare — Apple matchar varje donation. Även Apple-anställda kan nominera organisationer för företagsstöd.",
        contact_url="https://www.apple.com/philanthropy",
        contact_email="Se Apples interna giving-program",
    ),
    FundingSource(
        id="seb-stiftelsen",
        name="SEB Stiftelsen",
        full_name="Stiftelsen SEB",
        category="finans-bank",
        country="Sverige",
        max_amount="500 000 SEK",
        is_recurring=True,
        recurring_details="Ansökan en gång per år",
        deadline="Vanligtvis september–oktober",
        difficulty="Medium",
        eligibility="Svenska ideella organisationer med sociala ändamål, inkl. barn och unga.",
        tip="SEB-stiftelsen prioriterar projekt med tydlig lokal förankring och mätbara resultat.",
        contact_url="https://sebstiftelsen.se",
        contact_email="stiftelsen@seb.se",
    ),
    FundingSource(
        id="folksam-trygga",
        name="Folksam — Trygga barnen",
        full_name="Folksam ömsesidig sakförsäkring",
        category="finans-bank",
        country="Sverige",
        max_amount="300 000 SEK",
        is_recurring=True,
        recurring_details="Löpande ansökningar, beslut kvartalsvis",
        deadline="Löpande",
        difficulty="Låg",
        eligibility="Projekt som ökar tryggheten för barn i Sverige. Folksam beviljar bidrag från sin vinst.",
        tip="Folksam är mycket tillgängligt för välmotiverade barnrättsprojekt. Tydlig koppling till trygghet och säkerhet för barn i Sverige.",
        contact_url="https://www.folksam.se/om-folksam/hallbarhet/samhallsansvar/sponsring-och-bidrag",
        contact_email="samhallsansvar@folksam.se",
    ),
    FundingSource(
        id="sparbanksstiftelserna",
        name="Sparbanksstiftelserna",
        full_name="Sparbanksstiftelserna (lokal)",
        category="finans-bank",
        country="Sverige",
        max_amount="200 000 SEK",
        is_recurring=True,
        recurring_details="Löpande lokala ansökningar",
        deadline="Varierar per stiftelse",
        difficulty="Låg",
        eligibility="Lokala organisationer i respektive sparbanks verksamhetsområde.",
        tip="Varje sparbank har sin egen stiftelse med lokala medel. Ansök till stiftelsen i det/de län GCF är verksamt. Stark lokal förankring krävs.",
        contact_url="https://www.sparbankernas.se/om-oss/sparbanksstiftelserna.html",
        contact_email="Se respektive sparbanks webbplats",
    ),
    FundingSource(
        id="handelsbanken-sht",
        name="Handelsbankens Stiftelser",
        full_name="Jan Wallanders och Tom Hedelius stiftelse m.fl.",
        category="finans-bank",
        country="Sverige",
        max_amount="1 000 000 SEK",
        is_recurring=True,
        recurring_details="Ansökan en gång per år för forskningsstöd",
        deadline="Vanligtvis januari–februari",
        difficulty="Hög",
        eligibility="Primärt forskning och akademi. NGO kan söka i samarbete med akademiska institutioner.",
        tip="Handelsbankens stiftelser fokuserar på forskning. Koppla GCF till ett universitetsprojekt för att kvalificera.",
        contact_url="https://www.handelsbankenshuvudstiftelse.se",
        contact_email="stiftelser@handelsbanken.se",
    ),
    FundingSource(
        id="diakonia",
        name="Diakonia",
        full_name="Diakonia",
        category="kyrka-trossamfund",
        country="Sverige / Global",
        max_amount="2 000 000 SEK",
        is_recurring=False,
        recurring_details="Partnerorganisationer söker via ramavtal med Sida",
        deadline="Kontakta Diakonia för partnerskap",
        difficulty="Hög",
        eligibility="Organisationer som delar Diakonias värderingar — mänskliga rättigheter, demokrati och jämlikhet.",
        tip="Diakonia är en Sida-ramorganisation. GCF kan bli implementeringspartner och dela Diakonias Sida-finansiering. Kräver långsiktig relation.",
        contact_url="https://www.diakonia.se/for-organisationer/bli-partner",
        contact_email="partner@diakonia.se",
    ),
    FundingSource(
        id="svenska-kyrkan-int",
        name="Svenska kyrkan — Internationellt",
        full_name="Svenska kyrkans internationella arbete",
        category="kyrka-trossamfund",
        country="Sverige / Global",
        max_amount="1 000 000 SEK",
        is_recurring=False,
        recurring_details="Partnerskap med fokus på internationellt arbete",
        deadline="Kontakta direkt",
        difficulty="Hög",
        eligibility="Organisationer som arbetar med mänskliga rättigheter och humanitärt arbete internationellt.",
        tip="Svenska kyrkan finansierar internationellt barnrättsarbete via sin internationella avdelning (ACT-nätverket). Lokal kyrkkontakt kan öppna dörrar.",
        contact_url="https://www.svenskakyrkan.se/internationelltarbete",
        contact_email="internationellt@svenskakyrkan.se",
    ),
    FundingSource(
        id="act-alliance",
        name="ACT Alliance",
        full_name="Action by Churches Together Alliance",
        category="kyrka-trossamfund",
        country="Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Humanitärt och utvecklingsarbete via nätverket",
        deadline="Varierar per utlysning",
        difficulty="Hög",
        eligibility="Organisationer i ACT-nätverket. GCF behöver bli ACT-medlem eller partnera med en befintlig ACT-organisation.",
        tip="Bli ACT Alliance-observatör som steg mot fullt medlemskap. Nätverket ger tillgång till global finansiering och partnerskap.",
        contact_url="https://actalliance.org/who-we-are/membership",
        contact_email="info@actalliance.org",
    ),
    FundingSource(
        id="caritas-europa",
        name="Caritas Europa",
        full_name="Caritas Europa",
        category="kyrka-trossamfund",
        country="Europa",
        max_amount="300 000 EUR",
        is_recurring=False,
        recurring_details="Projektfinansiering via EU-program och egna fonder",
        deadline="Varierar",
        difficulty="Hög",
        eligibility="Organisationer med koppling till katolsk socialvård eller gemensamma värderingar.",
        tip="Caritas Europa administrerar EU-fondmedel till ideella. Bra ingång om GCF vill nå EU-finansiering via en etablerad mellanhand.",
        contact_url="https://www.caritas.eu/partnerships",
        contact_email="caritas.europa@caritas.eu",
    ),
    FundingSource(
        id="radiohjälpen",
        name="Radiohjälpen",
        full_name="Stiftelsen Radiohjälpen",
        category="lotteri-insamling",
        country="Sverige",
        max_amount="10 000 000 SEK",
        is_recurring=True,
        recurring_details="Ansökan inför Världens Barn och andra insamlingar",
        deadline="Vanligtvis december–januari för Världens Barn",
        difficulty="Hög",
        eligibility="Svenska ideella organisationer med internationellt barnrättsarbete. Kräver 90-konto och granskad av FRII.",
        tip="Världens Barn är SVT/SR:s stora insamling. Kräver att GCF är godkänd av Radiohjälpen — börja med att skaffa 90-konto och FRII-certifiering.",
        contact_url="https://www.radiohjalpen.se/om-oss/ansoka-om-stod",
        contact_email="radiohjalpen@svt.se",
    ),
    FundingSource(
        id="fralsningsarmen",
        name="Frälsningsarmén — Projektbidrag",
        full_name="Frälsningsarmén",
        category="lotteri-insamling",
        country="Sverige",
        max_amount="200 000 SEK",
        is_recurring=False,
        recurring_details="Samarbetsprojekt",
        deadline="Löpande dialog",
        difficulty="Medium",
        eligibility="Kompletterande organisationer till Frälsningsarméns sociala arbete med barn och familjer.",
        tip="Frälsningsarmén är mer intresserade av samarbete och gemensamma projekt än ren bidragsgivning. Identifiera gemensamma målgrupper.",
        contact_url="https://www.fralsningsarmen.se/om-oss/samarbeta-med-oss",
        contact_email="info@fralsningsarmen.se",
    ),
    FundingSource(
        id="insamlingsnamnden",
        name="Insamlingsnämnden",
        full_name="Stiftelsen Insamlingsnämnden",
        category="lotteri-insamling",
        country="Sverige",
        max_amount="100 000 SEK",
        is_recurring=False,
        recurring_details="Löpande ansökningar",
        deadline="Löpande",
        difficulty="Låg",
        eligibility="Registrerade svenska ideella organisationer.",
        tip="Liten men tillgänglig stiftelse. Låg konkurrens. Bra för att finansiera specifika projekt med tydlig lokal nytta.",
        contact_url="https://insamlingsnamnden.se",
        contact_email="info@insamlingsnamnden.se",
    ),
    FundingSource(
        id="vetenskapsradet",
        name="Vetenskapsrådet",
        full_name="Vetenskapsrådet",
        category="forskning-akademi",
        country="Sverige",
        max_amount="3 000 000 SEK",
        is_recurring=True,
        recurring_details="Utlysningar 2–3 gånger per år",
        deadline="Se vr.se för aktuella utlysningar",
        difficulty="Hög",
        eligibility="Kräver akademisk PI (Principal Investigator). NGO kan vara samarbetspart i praktiknära forskning.",
        tip="Etablera en forskningsrelation med ett lärosäte. Vetenskapsrådet finansierar praktiknära forskning och utbildningsvetenskap — koppling till barnrättsarbete är möjlig.",
        contact_url="https://www.vr.se/soka-finansiering",
        contact_email="info@vr.se",
    ),
    FundingSource(
        id="vinnova",
        name="Vinnova — Samhällsinnovation",
        full_name="Vinnova — Sveriges innovationsmyndighet",
        category="forskning-akademi",
        country="Sverige",
        max_amount="3 000 000 SEK",
        is_recurring=True,
        recurring_details="Utlysningar löpande inom olika program",
        deadline="Se vinnova.se för aktuella utlysningar",
        difficulty="Hög",
        eligibility="Organisationer som driver innovation för samhällsnytta. NGO kan söka, gärna i konsortium.",
        tip="Vinnova finansierar innovativa lösningar på samhällsproblem. Digitala verktyg för barnrättsarbete, AI-baserade system eller nya metodiker kan kvalificera.",
        contact_url="https://www.vinnova.se/finansiering",
        contact_email="info@vinnova.se",
    ),
    FundingSource(
        id="horizon-europe",
        name="Horizon Europe",
        full_name="EU:s Horizon Europe",
        category="forskning-akademi",
        country="EU / Global",
        max_amount="5 000 000 EUR",
        is_recurring=True,
        recurring_details="Löpande utlysningar i Work Programme 2024–2027",
        deadline="Se ec.europa.eu/info/funding-tenders",
        difficulty="Hög",
        eligibility="Konsortier med minst 3 partners från 3 EU-länder. NGO kan vara partner, akademi måste leda.",
        tip="Kluster 2 (Kultur, kreativitet, inklusivt samhälle) och Kluster 3 (Civilt skydd) har calls relevanta för barnrättsarbete. Hitta akademiska partners via EURAXESS.",
        contact_url="https://ec.europa.eu/info/funding-tenders/opportunities/portal",
        contact_email="Se aktuell utlysning på portalen",
    ),
    FundingSource(
        id="brottsofferfonden",
        name="Brottsofferfonden",
        full_name="Brottsofferfonden",
        category="ovaentad",
        country="Sverige",
        max_amount="500 000 SEK",
        is_recurring=True,
        recurring_details="Utlysningar 1–2 gånger per år",
        deadline="Vanligtvis mars och september",
        difficulty="Medium",
        eligibility="Organisationer som stöder brottsoffer, inkl. barn som utsatts för brott.",
        tip="Brottsofferfonden finansieras av bötesmedel från dömda brottslingar — direkt relevant för GCF. Ansök om projekt som stödjer barn som utsatts för brott.",
        contact_url="https://www.brottsoffermyndigheten.se/brottsofferfonden",
        contact_email="registrator@brottsoffermyndigheten.se",
    ),
    FundingSource(
        id="rotary-foundation",
        name="Rotary Foundation — Global Grants",
        full_name="The Rotary Foundation",
        category="ovaentad",
        country="Global",
        max_amount="500 000 USD",
        is_recurring=False,
        recurring_details="Löpande ansökningar via lokala Rotaryklubbar",
        deadline="Löpande — ansök via lokal Rotaryklubb",
        difficulty="Medium",
        eligibility="Projekt inom fred, vatten, hälsa, utbildning och ekonomisk utveckling. Kräver partnerskap med Rotaryklubb i Sverige och destinationsland.",
        tip="Kontakta din lokala Rotaryklubb i Kalmar eller Stockholm. Global Grants finansierar projekt från 30 000 USD. Rotarians i Rotary är ofta välvilligheten generösa mot välmotiverade söknanden.",
        contact_url="https://www.rotary.org/en/rotary-foundation/grants/global-grants",
        contact_email="rotaryfoundation@rotary.org",
    ),
    FundingSource(
        id="lions-foundation",
        name="Lions Clubs — LCIF",
        full_name="Lions Clubs International Foundation",
        category="ovaentad",
        country="Global",
        max_amount="100 000 USD",
        is_recurring=False,
        recurring_details="Löpande ansökningar via lokala Lions-klubbar",
        deadline="Löpande",
        difficulty="Låg",
        eligibility="Humanitära projekt, inkl. barnsyn och ungdomsutveckling. Kräver partnerskap med lokal Lions-klubb.",
        tip="Lions finns i de flesta svenska kommuner. Personlig relation med den lokala klubben är avgörande. Börja lokalt och bygg upp till nationell/internationell ansökan.",
        contact_url="https://www.lionsclubs.org/en/resources-for-members/resource-center/lcif-grants",
        contact_email="lcif@lionsclubs.org",
    ),
    FundingSource(
        id="soroptimist",
        name="Soroptimist International",
        full_name="Soroptimist International",
        category="ovaentad",
        country="Global",
        max_amount="50 000 USD",
        is_recurring=True,
        recurring_details="Utlysningar för projekt som stärker flickor och kvinnor",
        deadline="Varierar per program",
        difficulty="Låg",
        eligibility="Projekt som stärker flickors och kvinnors rättigheter och möjligheter.",
        tip="Soroptimist är okänd men engagerad. Kontakta din lokala Soroptimist-klubb. Stark matchning med flickors rättigheter och utbildning.",
        contact_url="https://www.soroptimistsweden.se",
        contact_email="info@soroptimistsweden.se",
    ),
    FundingSource(
        id="schwab-foundation",
        name="Schwab Foundation (WEF)",
        full_name="Schwab Foundation for Social Entrepreneurship",
        category="ovaentad",
        country="Global",
        max_amount="Nominering ger tillgång till WEF-nätverk",
        is_recurring=False,
        recurring_details="Nominering en gång per år",
        deadline="Nominering: april varje år",
        difficulty="Hög",
        eligibility="Sociala entreprenörer med bevisad impact i stor skala. Kräver en nominerande organisation.",
        tip="Schwab Foundation-utmärkelsen ger tillgång till Davos och WEF-nätverket — värdefullt för fundraising. Fokusera på att bygga impact-data.",
        contact_url="https://www.schwabfound.org/apply",
        contact_email="schwabfound@weforum.org",
    ),
    FundingSource(
        id="skoll-foundation",
        name="Skoll Foundation",
        full_name="Skoll Foundation",
        category="ovaentad",
        country="Global",
        max_amount="1 500 000 USD",
        is_recurring=False,
        recurring_details="Inbjudningsbaserat — Skoll Award",
        deadline="Nominering: oktober varje år",
        difficulty="Hög",
        eligibility="Sociala entrepreneurs med systemförändrande impact. Skoll Award ger $1.5M + nätverkstillgång.",
        tip="Skoll Forum i Oxford är ett av världens viktigaste nätverk för social innovation. Bygg synlighet och impact-data inför nominering.",
        contact_url="https://skoll.org/skoll-award",
        contact_email="apply@skollfoundation.org",
    ),
    FundingSource(
        id="ashoka",
        name="Ashoka — Social Entrepreneurs",
        full_name="Ashoka: Innovators for the Public",
        category="ovaentad",
        country="Global",
        max_amount="100 000 USD",
        is_recurring=False,
        recurring_details="Löpande nominering av Ashoka Fellows",
        deadline="Löpande",
        difficulty="Hög",
        eligibility="Individer med systemförändrande sociala innovationer. Stipendium till GCF:s grundare/ledare snarare än organisationen.",
        tip="Om GCF:s ordförande eller grundare har en systemförändrande vision — nominera dem som Ashoka Fellow. Stipendiet och nätverket är transformativt.",
        contact_url="https://www.ashoka.org/sv-se/program/ashoka-fellows",
        contact_email="info@ashoka.org",
    ),
    FundingSource(
        id="nesta",
        name="Nesta",
        full_name="Nesta",
        category="ovaentad",
        country="UK / Europa",
        max_amount="300 000 GBP",
        is_recurring=False,
        recurring_details="Specifika utlysningar och partnerskap",
        deadline="Varierar",
        difficulty="Hög",
        eligibility="Innovativa organisationer med datadrivna lösningar på samhällsproblem.",
        tip="Nesta finansierar datadrivna sociala innovationer. AI-baserat arbete för barnrättsarbete är ett starkt argument.",
        contact_url="https://www.nesta.org.uk/funding",
        contact_email="hello@nesta.org.uk",
    ),
    FundingSource(
        id="kriminalvarden",
        name="Kriminalvården — Samarbetsprojekt",
        full_name="Kriminalvården",
        category="ovaentad",
        country="Sverige",
        max_amount="300 000 SEK",
        is_recurring=False,
        recurring_details="Projekt kopplade till återfallsprevention",
        deadline="Kontakta regionalt",
        difficulty="Medium",
        eligibility="Organisationer som kompletterar Kriminalvårdens arbete med återfallsprevention och offer-perspektiv.",
        tip="Kriminalvården har medel för externa samarbetsprojekt, särskilt kring barns perspektiv som anhöriga till intagna och förövarrehabilitering.",
        contact_url="https://www.kriminalvarden.se/om-kriminalvarden/samarbete",
        contact_email="huvudkontoret@kriminalvarden.se",
    ),
    FundingSource(
        id="gaming-charity",
        name="ESL Gaming / Streamers (Charity Events)",
        full_name="Gaming & Esport Charity",
        category="ovaentad",
        country="Global",
        max_amount="Obegränsat (insamlingsbaserat)",
        is_recurring=False,
        recurring_details="Kampanjbaserat",
        deadline="Planera 6 månader i förväg",
        difficulty="Låg",
        eligibility="Alla registrerade välgörenhetsorganisationer. Kräver engagerande berättelse och digital närvaro.",
        tip="Charity streams via Twitch Charity och spelturneringar med donationsmål kan generera 100k–1M+ SEK. Engagera en välkänd svensk streamer eller esportorganisation.",
        contact_url="https://help.twitch.tv/s/article/charity-campaigns",
        contact_email="charity@twitch.tv",
    ),
    FundingSource(
        id="omidyar-network",
        name="Omidyar Network",
        full_name="Omidyar Network",
        category="ovaentad",
        country="Global",
        max_amount="1 000 000 USD",
        is_recurring=False,
        recurring_details="Inbjudningsbaserat",
        deadline="Inbjudningsbaserat",
        difficulty="Hög",
        eligibility="Organisationer med fokus på digital rättvisa, demokrati och ekonomisk inkludering.",
        tip="Omidyar Network investerar i organisationer som förändrar system. Barns digitala rättigheter är ett växande fokusområde.",
        contact_url="https://omidyar.com/our-work/apply",
        contact_email="info@omidyar.com",
    ),
    FundingSource(
        id="google-ad-grants",
        name="Google Ad Grants",
        full_name="Google Ad Grants for Nonprofits",
        category="ovaentad",
        country="Global",
        max_amount="120 000 USD/år (i annonsvärde)",
        is_recurring=True,
        recurring_details="Löpande — $10 000/mån i Google Ads-kredit",
        deadline="Ansök när som helst",
        difficulty="Låg",
        eligibility="Registrerade ideella organisationer med aktiv webbplats. Ej myndigheter, sjukhus eller skolor.",
        tip="ANSÖK OMEDELBART. $10 000/mån i gratis Google-annonsering kan driva donationer, volontärer och synlighet. En av de mest underutnyttjade finansieringskällorna för NGOs.",
        contact_url="https://www.google.com/grants",
        contact_email="nonprofits@google.com",
    ),
]


def funding_sources_as_dicts() -> list[dict[str, str | bool]]:
    """Return JSON-compatible dictionaries for exports and uploads."""
    return [asdict(source) for source in FUNDING_SOURCES]
